version: 2
jobs:

  xcode_9.0:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: git submodule update --init --recursive
      - run: xcodebuild -workspace LinuxSupportForXcode.xcworkspace -scheme LinuxSupportForXcode install DSTROOT=~ CODE_SIGN_IDENTITY=""|xcpretty

workflows:
  version: 2
  workflow:
    jobs:
      - xcode_9.0
